#!/bin/bash

source "$HOME/.cache/wal/colors.sh"

# Strip # from colors for Hyprland
bg=${background#\#}
fg=${foreground#\#}
c0=${color0#\#}
c1=${color1#\#}
c2=${color2#\#}
c3=${color3#\#}
c4=${color4#\#}
c5=${color5#\#}
c6=${color6#\#}
c7=${color7#\#}
c8=${color8#\#}
c9=${color9#\#}
c10=${color10#\#}
c11=${color11#\#}
c12=${color12#\#}
c13=${color13#\#}
c14=${color14#\#}
c15=${color15#\#}

cat > "$HOME/.cache/wal/colors-hyprland.conf" <<EOF
# AUTOGENERATED BY PYWAL

\$bg = $bg
\$fg = $fg
\$color0 = $c0
\$color1 = $c1
\$color2 = $c2
\$color3 = $c3
\$color4 = $c4
\$color5 = $c5
\$color6 = $c6
\$color7 = $c7
\$color8 = $c8
\$color9 = $c9
\$color10 = $c10
\$color11 = $c11
\$color12 = $c12
\$color13 = $c13
\$color14 = $c14
\$color15 = $c15

general {
    col.active_border = rgb(\$color4)
    col.inactive_border = rgb(\$color8)
}
EOF

hyprctl reload
