#!/bin/bash

source "$HOME/.cache/wal/colors.sh"

# Strip # from colors for Hyprland
bg=${background#\#}
fg=${foreground#\#}
c0=${color0#\#}
c1=${color1#\#}
c2=${color2#\#}
c3=${color3#\#}
c4=${color4#\#}
c5=${color5#\#}
c6=${color6#\#}
c7=${color7#\#}
c8=${color8#\#}
c9=${color9#\#}
c10=${color10#\#}
c11=${color11#\#}
c12=${color12#\#}
c13=${color13#\#}
c14=${color14#\#}
c15=${color15#\#}

cat > "$HOME/.cache/wal/colors-hyprland.lua" <<EOF
-- AUTOGENERATED BY PYWAL

local bg = $bg
local fg = $fg
local color0 = $c0
local = $c1
local color2 = $c2
local color3 = $c3
local color4 = $c4
local color5 = $c5
local color6 = $c6
local color7 = $c7
local color8 = $c8
local color9 = $c9
local color10 = $c10
local color11 = $c11
local color12 = $c12
local color13 = $c13
local color14 = $c14
local color15 = $c15

EOF

hyprctl reload
