#/// HYPR ///

source = ~/.config/hypr/assets/keybinds.conf
source = ~/.config/hypr/assets/decoration.conf 
source = ~/.cache/wal/colors-hyprland.conf


monitor = ,preferred,auto,1

#---------- AUTOSTARST ----------
exec-once = nm-applet
exec-once = waybar
exec-once = awww-daemon 
exec-once = mako
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = QT_QPA_PLATFORMTHEME,kde
env = QT_QPA_PLATFORM,wayland

exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"


# ---------- WM BEHAVIOR ----------
general {
    layout = dwindle
    resize_on_border = false
    allow_tearing = false
}

# ---------- INPUT ----------
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}


device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# ---------- RULES ----------
windowrule = match:class ^(chromium)$, float 1
windowrule = match:class ^(chromium)$, center 1
windowrule = match:class ^(chromium)$, size 1080 720

windowrule = match:class ^(Spotify)$, float 1
windowrule = match:class ^(Spotify)$, center 1
windowrule = match:class ^(Spotify)$, size 800 680
